version: '3.6'

services:
  db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_DB=nest-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5445:5432"
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-north-1
      - EDGE_PORT=4566
    ports:
      - '4566-4583:4566-4583'
      - '8055:8080'
    volumes:
      - localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db:
    driver: local
  localstack:
    driver: local
