#!/bin/bash

PROFILE=localstack
AWS_STORAGE_ACCESS_KEY_ID=default
AWS_STORAGE_SECRET_ACCESS_KEY=default
AWS_STORAGE_REGION=eu-north-1
AWS_ENDPOINT=http://localhost:4566

echo ''

# SNS + SQS

function create-sns-topic() {
  aws sns create-topic  \
    --profile $PROFILE \
    --endpoint-url $AWS_ENDPOINT \
    --name $1 | jq -r '.TopicArn'
}

function create-sqs-queue() {
  local queue_url=$(aws sqs create-queue \
    --profile $PROFILE \
    --endpoint-url $AWS_ENDPOINT \
    --queue-name $1 | jq -r '.QueueUrl'
  )

  aws sqs get-queue-attributes \
    --profile $PROFILE \
    --endpoint-url $AWS_ENDPOINT \
    --queue-url $queue_url \
    --attribute-names QueueArn | jq -r '.Attributes.QueueArn'
}

echo "Foo jobs queue: $(create-sqs-queue 'foo-jobs')"

echo "Bar jobs queue: $(create-sqs-queue 'bar-jobs')"
